openapi: 3.0.2

info:
  title: Swagger Petstore - OpenAPI 3.0
  description:
    "This is a sample Pet Store Server based on the OpenAPI 3.0 specification.\
    \  You can find out more about\nSwagger at [http://swagger.io](http://swagger.io).\
    \ In the third iteration of the pet store, we've switched to the design first\
    \ approach!\nYou can now help us improve the API whether it's by making changes\
    \ to the definition itself or to the code.\nThat way, with time, we can improve\
    \ the API in general, and expose some of the new features in OAS3.\n\nSome useful\
    \ links:\n- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)\n\
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)"
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.6

externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io

servers:
  - url: http://localhost:3000

tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Operations about user

paths:
  # pet
  /pet:
    $ref: ./paths/pet/pet.yml
  /pet/findByStatus:
    $ref: ./paths/pet/pet-find-by-status.yml
  /pet/findByTags:
    $ref: ./paths/pet/pet-find-by-tags.yml
  /pet/{petId}:
    $ref: ./paths/pet/pet-pet-id.yml
  /pet/{petId}/uploadImage:
    $ref: ./paths/pet/pet-pet-id-upload-image.yml
  # store
  /store/inventory:
    $ref: ./paths/store/store-inventory.yml
  /store/order:
    $ref: ./paths/store/store-order.yml
  /store/order/{orderId}:
    $ref: ./paths/store/store-order-order-id.yml

# 暫定
components:
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: "./components/schemas/pet.yml"
        application/xml:
          schema:
            $ref: "./components/schemas/pet.yml"
    UserArray:
      description: List of user object
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "./components/schemas/user.yml"
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
